variables:
  APPNAME: ${CI_PROJECT_NAME}
  DEMO_URL: 'demo.finpo.com.tw'
  PRODUCTION_URL: 'alpaca.finpo.com.tw'

image: node:10-alpine

cache:
  paths:
  - node_modules/
  
stages:
  - install
  - test
  - review
  - production

build:
  stage: install
  script:
    - yarn install

test_1_lint:
  stage: test
  script:
    - yarn install
    - yarn run lint

test_2_build:
  stage: test
  script:
    - yarn install
    - yarn run build

# review:
#   image: docker:git
#   stage: review
#   services:
#     - docker:dind
#   script:
#   - mkdir -p ~/.ssh
#   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
#   - chmod 600 ~/.ssh/id_rsa
#   - ssh-keyscan -H ${DEMO_URL} >> ~/.ssh/known_hosts
#   - 'echo -e "User-agent: *\nDisallow: /\n" > static/robots.txt'
#   - docker build --build-arg ENV_FILE=${CI_JOB_STAGE} -t dokku/${APPNAME}:latest . && docker save dokku/${APPNAME}:latest | ssh ausir@${DEMO_URL} "sudo docker load && dokku tags:deploy ${APPNAME} latest"
#   only:
#     - master

# production:
#   image: docker:git
#   stage: production
#   services:
#     - docker:dind
#   script:
#   - mkdir -p ~/.ssh
#   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
#   - chmod 600 ~/.ssh/id_rsa
#   - ssh-keyscan -H ${PRODUCTION_URL} >> ~/.ssh/known_hosts
#   - docker build --build-arg ENV_FILE=${CI_JOB_STAGE} -t dokku/${APPNAME}:latest . && docker save dokku/${APPNAME}:latest | ssh ausir@${PRODUCTION_URL} "sudo docker load && dokku tags:deploy ${APPNAME} latest"
#   only:
#     - production
